apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust-final
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow

  action: Block

  severity: 10
  message: "Zero-trust policy for Wisecow: only the app and its minimal dependencies allowed"

  file:
    matchPaths:
      - path: /app/wisecow.sh
        action: Allow
      - path: /app/response
        action: Allow
      - path: /app/config/*
        action: Allow
      - path: /app/logs/*
        action: Allow
      - path: /usr/games/fortune
        action: Allow
      - path: /usr/games/cowsay
        action: Allow
      - path: /bin/nc
        action: Allow
      - path: /usr/bin/nc
        action: Allow
    matchDirectories:
      - dir: /
        recursive: true
        action: Block
  process:
    matchPaths:
      - execname: wisecow.sh
        action: Allow
      - execname: bash
        action: Allow
      - execname: fortune
        action: Allow
      - execname: cowsay
        action: Allow
      - execname: nc
        action: Allow
    matchDirectories:
      - dir: /
        recursive: true
        action: Block

  network:
    matchProtocols:
      - protocol: tcp
        fromSource:
          - path: /bin/nc
          - path: /usr/bin/nc
        action: Allow
      - protocol: udp
        action: Block
      - protocol: icmp
        action: Block
